engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      javascript:
      ruby:
        mass_threshold: 30
  eslint:
    enabled: true
  golint:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/LineLength:
        enabled: false
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 100
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- app/assets/javascripts/handlebars.js
- coverage/**/*
- spec/**/*
- test/**/*
- "**/vendor/**/*"
- bin
- client/src/semantic-ui
- config
- db
