env:
  global:
    - CC_TEST_REPORTER_ID=73c65f5c12d49d807064c1ad93ac5abfb9f7b0b7965261c27ddfbb012ba0e020
language: ruby
rvm:
  - 2.4.2
install:
  - bundle install
before_script:
  - bundle exec rake db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ../cc-test-reporter
  - chmod +x ../cc-test-reporter
script:
  - ../cc-test-reporter before-build
  - bundle exec rspec
after_script:
  - ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
